### ISSUE TITLE
`extraStyling` warnings in dev tools

### ISSUE THREAD

**Issue by gareth-j** [openghg/decc_dashboard#36]
We're getting an error in devtools:

`Warning: React does not recognize the `extraStyling` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `extrastyling` instead.`

We're passing in this styling to the `TextButton` component. Maybe we can avoid this by using separate CSS classes.

**Comment by SutarPrasad** [comment]
Most of the text Buttons are replaced on the dashboard with Material UI. So upon completion of other PRs, I'll revisit this and check for it.

**Comment by SutarPrasad** [comment]
The following issue has been addressed in 

- [ ] #30 
The variable declaration is changed from camelcase to lowercase
