### ISSUE TITLE
Unable to select different emissions in `EmissionsBox`

### ISSUE THREAD

**Issue by gareth-j** [openghg/decc_dashboard#37]
I can't select different emission types on the explainer page, I get the following error:

```
$(name) not in images 2 EmissionsBox.js:58
    setImage EmissionsBox.js:58
    React 14
    unstable_runWithPriority scheduler.development.js:468
    React 4
```

**Comment by SutarPrasad** [comment]
This bug is now addressed in #30. Thanks for highlighting this. It will be closed on completion of #30
